owner: iuc
name: flow_overview
description: generates an overview of the flow analysis results
long_description: |
    **Input**
    Tool input is a tab-separated file containing markers fluorescence intensities for each event as well as population and is generated as part of FLOCK or CrossSample output.  If the option is selected, flowCL is used to associate populations defined by FLOCK to a Cell Ontology term. Marker names do need to be in the Cell Ontology for flowCL to run.

    **Output**
    The output is an interactive page with multiple tabs that allows visualization of the data.

    https://www.immportgalaxy.org
categories:
    - Flow Cytometry Analysis
remote_repository_url: https://github.com/ImmPortDB/immport-galaxy-tools/tree/master/flowtools/flow_overview
type: unrestricted
